language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Cutewarriorlover
  username: __token__
  password:
    secure: jg2Y0aR6KlGJPLc1f8YlG2je9JrpOIjO6ArSfX7kLjrHj3E9HYCeoX74b3YZqhdaeIwtyeNT+e/rvZzhTdTXtbSbphY4ZNzfn9Vxcki9T7DFkQPGQDL9XtPWoUWDau6uwYuCZatk8OBvCICdSZ/i35kKHKyaGUSbaoHuqx97ep2CaLynep/dJIou9WTA4L84abfyWAQIDBeAswRHY6APcXK1Qp7XBael2ZV4yRR6kqH0FuQE9j5tjKBrfR8wCGeBn5HYMw2Gsnc0myKCXjFIgpUsb/wkcdqjFLF0Q8Ygz5SN7t2rS7z0oobP+9NsF91mMR4wE7EWTZkQTL1D8Wljb60iAKX7/rQQaiTNdAys6CTRrlgzEK/bvKhmr+zwfPBBz1QNvg1quLNGlGhwCZ9r3MKEcuuySByDFD/WFpS1mnnJPIVMO0TnSCrkB0d+zE3EEnjyg84A3oFy51kcTT6v15LHsy4LiUdKnws1xjo3VgY4SVYWiqGpdODMAzBuyup4l7+ON8hweIByQBIOmioVFOEONV9kFMdljb+6yitWIA6yvKRfyPQ2Uda2CEvm/QXaNhUg0TUH471/FOCMfdxJzOAhvLPCxtgTgO0Wy6ArP41NNdyqT5a6UZKx5DNt3u6MsiHqLorbKIR3UnzVwnBzJZx7FVoif15gcmZQPt5lzgM=
  on:
    tags: true
    repo: Cutewarriorlover/yaag-mme
    python: 3.8
